server:
  #配置eurekaServer的端口号
  port: 8761
eureka:
  client:
    service-url:
      #代表注册到eureka服务端的地址
      defaultZone: http://127.0.0.1:8761/eureka
      #该服务为注册中心，增加此行代表不在注册中心注册自己
    register-with-eureka: false
    #由于注册中心呢的职责是维护实例，为FALSE代表其不用去检索服务
    fetch-registry: false
    #配置主机名
  instance:
    hostname: peer1
    #配置服务名